extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass


func _on_close_button_up() -> void:
	get_tree().quit()


func _on_minimize_button_up() -> void:
	OS.shell_open("https://tenor.com/en-CA/view/free-smileys-faces-de-emoji-nope-no-nah-gif-16168307")
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MINIMIZED)


func _on_start_pressed() -> void:
	get_window().size = Vector2(0,0)
	get_window().position = Vector2(-100,-100)
