extends Node2D

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass
	

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	# The most important functionality
	if Input.is_action_just_pressed("G"):
		$Meow.play()


func _on_microgame_spawn_timer_timeout() -> void:
	print("WAAAHAHAHA MICROGAMES")
	
	# Spawn a microgame window
	var window_scene = preload("res://scenes/microgames/ad/ad_window.tscn")
	var window_instance = window_scene.instantiate()
	
	print(type_string(typeof(window_instance)))
	
	add_child(window_instance)
	
	# Randomize window position
	var screen_size = DisplayServer.screen_get_size()
	var window_x = randi_range(0, screen_size.x - window_instance.size.x)
	var window_y = randi_range(0, screen_size.y - window_instance.size.y)
	window_instance.position = Vector2(window_x, window_y)
	
	# Connect signals
	window_instance.win.connect(_on_microgame_win)
	

func _on_microgame_win(window: MicrogameWindow):
	print("yay")


func _on_fishin_win() -> void:
	$Fishin.visible = false
	$"Stock ticker".start()
	$"Microgame spawn timer".start()
	$Clippette.visible = true
	$"Score window (real)".visible = true
