extends Node2D


var earnings = Big.new(1, 100000)

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	var label = $Label
	label.text = "You made $%s\nYou lost $%s" % [earnings.toLongName(), earnings.toLongName()]
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass


func _on_minimize_button_up() -> void:
	OS.shell_open("https://youtu.be/0hpBKPbl0tk?si=I4ljc3fF5VrptriO")
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MINIMIZED)


func _on_close_button_up() -> void:
	get_tree().quit()
